name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci
        working-directory: backend  # se seu package.json estiver em backend

      - name: Run ESLint
        run: npx eslint .
        working-directory: backend